-- Migration: 007_create_agent_tables
-- Purpose: Persist agent chat threads, display messages, and tool calls

CREATE TABLE IF NOT EXISTS agent_threads (
    id TEXT PRIMARY KEY,                    -- UUID, generated by frontend
    title TEXT NOT NULL DEFAULT 'New chat', -- Auto-set from first user message
    connection_id TEXT NOT NULL,            -- Connection this thread belongs to
    database_name TEXT,                     -- Selected database at thread creation
    model TEXT NOT NULL,                    -- e.g. "claude-sonnet-4-6"
    effort TEXT NOT NULL DEFAULT 'auto',    -- auto | low | medium | high | max
    sdk_session_id TEXT,                    -- SDK JSONL session UUID (set after first turn)
    summary TEXT,                           -- Post-compaction summary (future use)
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_messages (
    id TEXT PRIMARY KEY,                    -- UUID
    thread_id TEXT NOT NULL REFERENCES agent_threads(id) ON DELETE CASCADE,
    role TEXT NOT NULL,                     -- "user" | "assistant"
    content TEXT NOT NULL DEFAULT '',
    thinking TEXT,                          -- Extended thinking content, if any
    timestamp INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_tool_calls (
    id TEXT PRIMARY KEY,                    -- toolId from SDK event
    thread_id TEXT NOT NULL REFERENCES agent_threads(id) ON DELETE CASCADE,
    tool_name TEXT NOT NULL,
    input TEXT NOT NULL DEFAULT '{}',       -- JSON-serialised input
    output TEXT,                            -- NULL while running
    status TEXT NOT NULL DEFAULT 'running', -- running | done | error
    started_at INTEGER NOT NULL,
    completed_at INTEGER
);

CREATE INDEX IF NOT EXISTS idx_agent_threads_connection ON agent_threads(connection_id);
CREATE INDEX IF NOT EXISTS idx_agent_messages_thread ON agent_messages(thread_id);
CREATE INDEX IF NOT EXISTS idx_agent_tool_calls_thread ON agent_tool_calls(thread_id);
