//! DDL generation commands — return CREATE statements for PostgreSQL objects.
//! All commands are read-only and connect live to the database.

use tauri::State;
use crate::{DatabaseState, ConnectionManagerState};
use log::debug;

use super::introspection_commands::pg_connect_for_commands;

#[tauri::command]
pub async fn get_table_ddl(
    connection_id: String,
    database: String,
    schema: String,
    table_name: String,
    db_state: State<'_, DatabaseState>,
    conn_state: State<'_, ConnectionManagerState>,
) -> Result<String, String> {
    let client = pg_connect_for_commands(&connection_id, &database, &db_state, &conn_state).await?;
    let qualified = format!("\"{}\".\"{}\"", schema, table_name);
    debug!("Generating DDL for table {}", qualified);

    // Get column definitions including identity/generated info
    let col_rows = client.query(
        "SELECT
            a.attname AS col_name,
            pg_catalog.format_type(a.atttypid, a.atttypmod) AS col_type,
            a.attnotnull AS not_null,
            pg_get_expr(d.adbin, d.adrelid) AS default_val,
            a.attidentity::text AS identity,        -- '' | 'a' (always) | 'd' (by default)
            a.attgenerated::text AS generated       -- '' | 's' (stored)
        FROM pg_attribute a
        LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
        WHERE a.attrelid = $1::regclass
          AND a.attnum > 0
          AND NOT a.attisdropped
        ORDER BY a.attnum",
        &[&qualified],
    ).await.map_err(|e| format!("Column query error for {}.{}: {}", schema, table_name, e))?;

    // Get constraints
    let con_rows = client.query(
        "SELECT conname, pg_get_constraintdef(oid) AS def
        FROM pg_constraint
        WHERE conrelid = $1::regclass
        ORDER BY contype, conname",
        &[&qualified],
    ).await.map_err(|e| format!("Constraint query error for {}.{}: {}", schema, table_name, e))?;

    // Build column definitions
    let mut parts: Vec<String> = col_rows.iter().map(|row| {
        let col_name: &str = row.get(0);
        let col_type: &str = row.get(1);
        let not_null: bool = row.get(2);
        let default_val: Option<&str> = row.get(3);
        let identity: &str = row.get(4);
        let generated: &str = row.get(5);

        let mut def = format!("    \"{}\" {}", col_name, col_type);

        // Identity columns: supersede DEFAULT
        if identity == "a" {
            def.push_str(" GENERATED ALWAYS AS IDENTITY");
        } else if identity == "d" {
            def.push_str(" GENERATED BY DEFAULT AS IDENTITY");
        } else if generated == "s" {
            // Stored generated column — expression is in default_val
            if let Some(expr) = default_val {
                def.push_str(&format!(" GENERATED ALWAYS AS ({}) STORED", expr));
            }
        } else {
            // Normal column: DEFAULT first, then NOT NULL (idiomatic PostgreSQL order)
            if let Some(d) = default_val {
                def.push_str(&format!(" DEFAULT {}", d));
            }
            if not_null {
                def.push_str(" NOT NULL");
            }
        }

        def
    }).collect();

    // Add constraint definitions
    for row in &con_rows {
        let con_name: &str = row.get(0);
        let con_def: &str = row.get(1);
        parts.push(format!("    CONSTRAINT \"{}\" {}", con_name, con_def));
    }

    Ok(format!(
        "CREATE TABLE \"{}\".\"{}\" (\n{}\n);",
        schema, table_name,
        parts.join(",\n")
    ))
}

#[tauri::command]
pub async fn get_view_definition(
    connection_id: String,
    database: String,
    schema: String,
    view_name: String,
    db_state: State<'_, DatabaseState>,
    conn_state: State<'_, ConnectionManagerState>,
) -> Result<String, String> {
    let client = pg_connect_for_commands(&connection_id, &database, &db_state, &conn_state).await?;
    debug!("Fetching view definition for {}.{}", schema, view_name);

    let row = client.query_one(
        "SELECT definition FROM pg_views WHERE schemaname = $1 AND viewname = $2",
        &[&schema, &view_name],
    ).await.map_err(|e| format!("View {}.{} not found: {}", schema, view_name, e))?;

    let definition: &str = row.get(0);
    Ok(format!("CREATE OR REPLACE VIEW \"{}\".\"{}\" AS\n{}", schema, view_name, definition.trim_end()))
}

#[tauri::command]
pub async fn get_matview_definition(
    connection_id: String,
    database: String,
    schema: String,
    view_name: String,
    db_state: State<'_, DatabaseState>,
    conn_state: State<'_, ConnectionManagerState>,
) -> Result<String, String> {
    let client = pg_connect_for_commands(&connection_id, &database, &db_state, &conn_state).await?;
    debug!("Fetching matview definition for {}.{}", schema, view_name);

    let row = client.query_one(
        "SELECT definition, ispopulated FROM pg_matviews WHERE schemaname = $1 AND matviewname = $2",
        &[&schema, &view_name],
    ).await.map_err(|e| format!("Materialized view {}.{} not found: {}", schema, view_name, e))?;

    let definition: &str = row.get(0);
    let is_populated: bool = row.get(1);
    let data_clause = if is_populated { "WITH DATA" } else { "WITH NO DATA" };

    Ok(format!(
        "CREATE MATERIALIZED VIEW \"{}\".\"{}\" AS\n{}\n{};",
        schema, view_name,
        definition.trim_end(),
        data_clause
    ))
}

#[tauri::command]
pub async fn get_function_ddl(
    connection_id: String,
    database: String,
    schema: String,
    function_name: String,
    db_state: State<'_, DatabaseState>,
    conn_state: State<'_, ConnectionManagerState>,
) -> Result<String, String> {
    let client = pg_connect_for_commands(&connection_id, &database, &db_state, &conn_state).await?;
    debug!("Fetching function DDL for {}.{}", schema, function_name);

    // pg_get_functiondef returns the complete CREATE OR REPLACE FUNCTION/PROCEDURE statement
    // Multiple rows = overloaded functions with different argument types
    let rows = client.query(
        "SELECT pg_get_functiondef(p.oid)
        FROM pg_proc p
        JOIN pg_namespace n ON p.pronamespace = n.oid
        WHERE n.nspname = $1 AND p.proname = $2
        ORDER BY p.oid",
        &[&schema, &function_name],
    ).await.map_err(|e| format!("Function {}.{} not found: {}", schema, function_name, e))?;

    if rows.is_empty() {
        return Err(format!("Function {}.{} not found", schema, function_name));
    }

    // Concatenate all overloads with a separator comment
    let ddls: Vec<String> = rows.iter().map(|row| row.get::<_, String>(0)).collect();
    if ddls.len() == 1 {
        Ok(ddls.into_iter().next().unwrap())
    } else {
        Ok(ddls.join("\n\n-- (overloaded function — next definition follows)\n\n"))
    }
}

#[tauri::command]
pub async fn get_sequence_ddl(
    connection_id: String,
    database: String,
    schema: String,
    sequence_name: String,
    db_state: State<'_, DatabaseState>,
    conn_state: State<'_, ConnectionManagerState>,
) -> Result<String, String> {
    let client = pg_connect_for_commands(&connection_id, &database, &db_state, &conn_state).await?;
    debug!("Fetching sequence DDL for {}.{}", schema, sequence_name);

    let row = client.query_one(
        "SELECT data_type::text, start_value, min_value, max_value, increment_by, cycle, cache_size
        FROM pg_sequences
        WHERE schemaname = $1 AND sequencename = $2",
        &[&schema, &sequence_name],
    ).await.map_err(|e| format!("Sequence {}.{} not found: {}", schema, sequence_name, e))?;

    let data_type: &str = row.get(0);
    let start: i64 = row.get(1);
    let min: i64 = row.get(2);
    let max: i64 = row.get(3);
    let increment: i64 = row.get(4);
    let cycle: bool = row.get(5);
    let cache: i64 = row.get(6);

    Ok(format!(
        "CREATE SEQUENCE \"{}\".\"{}\"
    AS {}
    START WITH {}
    INCREMENT BY {}
    MINVALUE {}
    MAXVALUE {}
    CACHE {}{};",
        schema, sequence_name, data_type, start, increment, min, max, cache,
        if cycle { "\n    CYCLE" } else { "\n    NO CYCLE" }
    ))
}

#[tauri::command]
pub async fn get_index_ddl(
    connection_id: String,
    database: String,
    schema: String,
    table_name: String,
    index_name: String,
    db_state: State<'_, DatabaseState>,
    conn_state: State<'_, ConnectionManagerState>,
) -> Result<String, String> {
    let client = pg_connect_for_commands(&connection_id, &database, &db_state, &conn_state).await?;
    debug!("Fetching index DDL for {}", index_name);

    let row = client.query_one(
        "SELECT indexdef FROM pg_indexes WHERE schemaname = $1 AND tablename = $2 AND indexname = $3",
        &[&schema, &table_name, &index_name],
    ).await.map_err(|e| format!("Index {} on {}.{} not found: {}", index_name, schema, table_name, e))?;

    Ok(row.get(0))
}

#[tauri::command]
pub async fn get_trigger_definition(
    connection_id: String,
    database: String,
    schema: String,
    table_name: String,
    trigger_name: String,
    db_state: State<'_, DatabaseState>,
    conn_state: State<'_, ConnectionManagerState>,
) -> Result<String, String> {
    let client = pg_connect_for_commands(&connection_id, &database, &db_state, &conn_state).await?;
    debug!("Fetching trigger definition for {}.{}", table_name, trigger_name);

    let row = client.query_one(
        "SELECT pg_get_triggerdef(t.oid, true)
        FROM pg_trigger t
        JOIN pg_class c ON c.oid = t.tgrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = $1 AND c.relname = $2 AND t.tgname = $3
          AND NOT t.tgisinternal",
        &[&schema, &table_name, &trigger_name],
    ).await.map_err(|e| format!("Trigger {} on {}.{} not found: {}", trigger_name, schema, table_name, e))?;

    Ok(row.get(0))
}

#[cfg(test)]
mod tests {
    fn build_sequence_ddl(
        schema: &str,
        name: &str,
        data_type: &str,
        start: i64,
        increment: i64,
        min: i64,
        max: i64,
        cache: i64,
        cycle: bool,
    ) -> String {
        format!(
            "CREATE SEQUENCE \"{}\".\"{}\"
    AS {}
    START WITH {}
    INCREMENT BY {}
    MINVALUE {}
    MAXVALUE {}
    CACHE {}{};",
            schema, name, data_type, start, increment, min, max, cache,
            if cycle { "\n    CYCLE" } else { "\n    NO CYCLE" }
        )
    }

    #[test]
    fn test_sequence_ddl_no_cycle() {
        let ddl = build_sequence_ddl("public", "users_id_seq", "bigint", 1, 1, 1, 9223372036854775807, 1, false);
        assert!(ddl.contains("CREATE SEQUENCE \"public\".\"users_id_seq\""));
        assert!(ddl.contains("AS bigint"));
        assert!(ddl.contains("NO CYCLE"));
        assert!(!ddl.contains("\n    CYCLE;"));
    }

    #[test]
    fn test_sequence_ddl_with_cycle() {
        let ddl = build_sequence_ddl("myschema", "order_seq", "integer", 100, 10, 1, 1000, 5, true);
        assert!(ddl.contains("CREATE SEQUENCE \"myschema\".\"order_seq\""));
        assert!(ddl.contains("START WITH 100"));
        assert!(ddl.contains("INCREMENT BY 10"));
        assert!(ddl.contains("CACHE 5"));
        assert!(ddl.contains("\n    CYCLE"));
    }
}
